### ISSUE TITLE
The Windows Experience 🪟

### ISSUE THREAD

**Issue by jspraul** [tobixen/plann#5]
Should be reproducible in Windows Sandbox:

- Start powershell allowing Scoop installation: `powershell -executionpolicy remotesigned`
- No one should run code from the internet like this: `iex "& {$(irm get.scoop.sh)} -RunAsAdmin"; scoop install git; scoop install python@3.11.1`
- `cd \ ; git clone https://github.com/tobixen/plann.git ; cd \plann ; python setup.py install`

Running plann indicates a dependency on PyYaml:
```
File "C:\Users\WDAGUtilityAccount\scoop\apps\python\current\Lib\site-packages\plann-0.15-py3.11.egg\plann\config.py", line 3, in <module>
ModuleNotFoundError: No module named 'yaml'
```
- `pip install pyyaml`

Running plann indicates a dependency on a HOME environment variable:
```
  File "C:\Users\WDAGUtilityAccount\scoop\apps\python\current\Lib\site-packages\plann-0.15-py3.11.egg\plann\cli.py", line 236, in <module>
  File "<frozen os>", line 679, in __getitem__
KeyError: 'HOME'
```
- `$Env:HOME="c:\plann"`

With those two missing pieces things seem to work.

Windows Sandbox seems to indicate Windows does have the combinable HOMEDRIVE + HOMEPATH environment variables.

**Comment by tobixen** [comment]
Thanks for your feedback.

The missing PyYAML is a bug that could have easily been spotted if I would have had github running tests for every commit.  I will set it up at some point in the not-too-far future.

The code referencing HOME has been sort of fixed:

```
-@click.option('-c', '--config-file', default=f"{os.environ['HOME']}/.config/calendar.conf")
+@click.option('-c', '--config-file', default=f"{os.environ.get('HOME')}/.config/calendar.conf")
```

... obviously the new default also won't work on "exotic OS distributions" (even asserting the presence of $HOME/.config may break on Linux).  Suggestions for a more robust default value here is welcome.  Anyway, file/directory not found is an expected exception so it should not break with a traceback anymore.  (I hope.  Did not test.  I really should write up lots of test code on this one - but currently I'm prioritizing to actually make something that is useful for me).

**Comment by jspraul** [comment]
Re-ran the steps provided and it's all clear.

**Comment by tobixen** [comment]
> Re-ran the steps provided and it's all clear.

thanks
